### ISSUE TITLE
Feature: RTE in short field

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#22]
please add the RTE to the subheader field or add a option to activate RTE for subheader. thanks

**Comment by derhecht** [comment]
sry, this doesn't make sense

**Comment by w010** [comment]
I think it makes a lot of sense, I got such task many times from various clients.
Of course this should be an option.

**Comment by Patta** [comment]
Sorry i mean in Short field, not in subheader ;)

**Comment by derhecht** [comment]
only because of clients requested something it doesn't make sense anyway BUT create a PR with a config option and code which reacts on it like @Patta requested and lets have a look?!

@Patta and your latest comment changes my answer a bit at all ;) May you could also create a PR? so in the end we may have 2 PRs with 2 features which would be nice for all of us?

**Comment by w010** [comment]
I think clients requests are the most important reason to add any functionality. To have something which repeats number of times built-in just to use and finally reduce a time of work.
